### ISSUE TITLE
Trouble running Make Analysis

### ISSUE THREAD

**Issue by gatlinnewhouse** [siddharthist/math389#2]
Maybe it's just my computer, here's the output I get:

``` bash
Overfull \hbox (21.49144pt too wide) in paragraph at lines 79--80
[]\OT1/cmtt/m/n/10 ## Warn-ing in file(file, "rt"): can-not open file 'cache-si
ze-data.csv': No such file

Overfull \hbox (26.7414pt too wide) in paragraph at lines 99--99
[]\OT1/cmtt/bx/n/10 ## Error in if (is.waive(data) || empty(data)) return(cbind
(data, PANEL = integer(0))):
Syntax Error: Invalid page count 0
! error:  (file figure/unnamed-chunk-1-1.pdf) (pdf inclusion): required page '1
' does not exist
!  ==> Fatal error occurred, no output PDF file produced!Makefile:15: recipe for target 'analysis' failed
make: *** [analysis] Error 1
```

**Comment by gatlinnewhouse** [comment]
@siddharthist

**Comment by langston-barrett** [comment]
Oh, sorry! I'll put this in the Makefile soon but for now run `make build` and then execute the executable. When it's done, it will have created the CSV file. Then run `make analysis`

**Comment by langston-barrett** [comment]
Fixed in https://github.com/siddharthist/math389/commit/2262c7f255932d5b393afc8dc825dec508d3c89d

**Comment by gatlinnewhouse** [comment]
``` bash
gatnewhou@laptop cache[master]$ make analysis
make: *** No rule to make target 'cache-size.gen.h', needed by 'build'.  Stop.
```

**Comment by langston-barrett** [comment]
Huh, I'm not having that issue.

**Comment by langston-barrett** [comment]
Do you see this in your Makefile?

```
%.gen.h: %.c ../../makeheaders.sh $(DEPS)
    bash ../../makeheaders.sh $<;
```

**Comment by gatlinnewhouse** [comment]
Yes I do

**Comment by langston-barrett** [comment]
Looks like that's a problem that Travis is also facing... I wonder what's different on my machine: https://travis-ci.org/siddharthist/math389

**Comment by gatlinnewhouse** [comment]
This recent commit 2a5dbc1 fixed it for me

**Comment by gatlinnewhouse** [comment]
It's currently searching for the size of the L1 cache

**Comment by langston-barrett** [comment]
I literally just forgot to upload a file: https://github.com/siddharthist/math389/commit/14dd8b11c32fc3f8dd0b45387969d3bcaa52b8d5

Sorry, Gatlin! Silly mistake on my part.
